### ISSUE TITLE
Use native `event.key` on Chrome versions >=56

### ISSUE THREAD

**Issue by marijnh** [marijnh/w3c-keyname#1]
See https://bugs.chromium.org/p/chromium/issues/detail?id=633838 and a8d1819f9c2c75762 . Once we're sure this is fixed, the code should detect the Chrome version and only apply the kludge for version <56.

**Comment by marijnh** [comment]
Still broken in 56.0.2914.3 dev (64-bit)

**Comment by tyrasd** [comment]
It works for me in 57.0.2925.0 dev (64-bit)

**Comment by marijnh** [comment]
Chrome 57 has finally arrived for Linux, so I was able to confirm this. Attached patch disables the workaround for Chrome versions >=57.
