### ISSUE TITLE
Package subpath './package.json' is not defined by "exports"

### ISSUE THREAD

**Issue by zwz** [marijnh/w3c-keyname#10]
I was using this package in https://github.com/sveltejs/sapper-template/tree/rollup
But it reports error:
```
Package subpath './package.json' is not defined by "exports" 
in <my-project-path>/node_modules/w3c-keyname/package.json
```

**Comment by marijnh** [comment]
Do you have a stack trace for the error? I guess someone is directly requiring package.json, which worked fine in a pre-node-14 world, but is likely to cause this error for packages that declare an `exports` field now. The best way to fix it is probably to adjust that package to just load and parse the file properly.

**Comment by zwz** [comment]
What I did is adding at the beginning of the file `sapper-template-rollup/src/routes/index.svelte`:
```
<script>
 import * as Key from  "w3c-keyname"   
</script>
```

And when I run `npm run dev`, it reports:
```
✗ server
Package subpath './package.json' is not defined by "exports" in /Users/rbx0999/project/sapper-template-rollup/node_modules/w3c-keyname/package.json
✗ client
Package subpath './package.json' is not defined by "exports" in /Users/rbx0999/project/sapper-template-rollup/node_modules/w3c-keyname/package.json
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'sapper-template-rollup/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by marijnh** [comment]
This seems to be an issue with rollup-plugin-svelte (see [this pr](https://github.com/sveltejs/rollup-plugin-svelte/pull/108), for example). I'm going to close this here.
