### ISSUE TITLE
Shift-Tab is "Unidentified"

### ISSUE THREAD

**Issue by FPurchess** [marijnh/w3c-keyname#13]
Binding `Shift-Tab` in prosemirror-keymap results in an unexpected behaviour originally cased by this package. Though the `KeyboardEvent` is clearly recognized as Tab with a shift-modifier (`event.keyCode === 9 && event.shiftKey`), the key is marked as `"Unidentified"`.

Here's the user agent (using prosemirror in https://github.com/tauri-apps/tauri):
`Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15`

However, I can confirm that the Tab gets detected in Firefox & Chrome thought.

**Comment by marijnh** [comment]
Funny, seems that mess of a browser sets `event.key` to `"Unidentified"` when shift is held for some reason. Attached patch allows `keyName` to ignore the `key` property in that case.

**Comment by FPurchess** [comment]
Thank @marijnh ❤️ much appreciated!
