### ISSUE TITLE
Possible wrong KeyNames on mac with Option key combinations

### ISSUE THREAD

**Issue by cyrillbrito** [marijnh/w3c-keyname#15]
On a mac system when I use the Option key modifier to write some special character the return of the `keyName` is the value of the underlaying hardware key instead of the actual character that is written.

I do have questions if this is the intended behaviour or not... Let me know if it is indeed a bug or an expected result.

I am using:
- OS: macOS Ventura
- Keyboard layout: US  (Also tried others and same thing append)
- Browser: Brave 1.49.120 / Chromium: 111.0.5563.64 (Also tried on Firefox and same thing append)
- Version: 2.2.6

**Video:**

https://user-images.githubusercontent.com/19173915/226334905-01cfb9ab-6b4e-4819-bdba-0533fb79bbf4.mov

---

[Code sandbox](https://codesandbox.io/s/w3c-keyname-f8d4r7?file=/index.html:241-247)

**Comment by marijnh** [comment]
This is an annoying thing that MacOS does, and unfortunately not something that a library like this (which doesn't know anything about the keyboard layout) can hide.
