### ISSUE TITLE
Deprecated and vulnerable version of rollup

### ISSUE THREAD

**Issue by kapustaikwas27** [marijnh/w3c-keyname#17]
DOM Clobbering Gadget found in rollup bundled scripts that leads to XSS

https://github.com/advisories/GHSA-gcx4-mw62-g8wm

**Comment by marijnh** [comment]
Since our build output doesn't reference `document.currentScript`, I don't think this vulnerability is an issue for this package. Attached patch upgrades Rollup to a current version.
