### ISSUE TITLE
Document the `base` export

### ISSUE THREAD

**Issue by justinfagnani** [marijnh/w3c-keyname#6]
I tried to convert CodeMirror 6's key handler to just use KeyboardEvent.key (only to workaround #5), and it seemed fine, except that I didn't know what the platform equivalent of `base` was.

**Comment by marijnh** [comment]
> and it seemed fine

Except on browsers that have broken support for `.key`, which are all IE versions (which uses some non-standard names) along with most browsers on macOS (which report the wrong names when some modifier keys are held). So unfortunately, we're going to continue to need this kludge for the time being.

Attached patch documents `base` and `shift`.

**Comment by justinfagnani** [comment]
> Except on browsers that have broken support for .key

Yeah, I knew it was likely problematic on other browsers, but even on Chrome I didn't know what the equivalent to `base` was.

Thanks for the notes!
