### ISSUE TITLE
Latest version doesn't seem to work in StackBlitz

### ISSUE THREAD

**Issue by PetarMetodiev** [marijnh/w3c-keyname#9]
Since version `2.2.3`, the package does not seem to work in StackBlitz - https://stackblitz.com/edit/typescript-zw2hah?file=index.ts

This is what I get in StackBlitz:
![image](https://user-images.githubusercontent.com/6378306/78338367-57b3c000-759b-11ea-84b9-fbebbe71c6ea.png)

The previous version(`2.2.2`) seems to be ok - https://stackblitz.com/edit/typescript-t9ezwm?file=index.ts

**Comment by marijnh** [comment]
File an issue with stackblitz. It probably can't deal with `.cjs` file extensions, but it should, since those are likely to become more common in the near future.

**Comment by PetarMetodiev** [comment]
I can't seem to find any information on `.cjs` extension on the internet. Is there any chance that you mean `.mjs`?
As far as I know CJS is an abbreviation for CommonJS which is a module format, but does not have a separate file format.

**Comment by marijnh** [comment]
It is used by node to force CommonJS modules. See https://nodejs.org/dist/latest-v13.x/docs/api/esm.html#esm_enabling .
